trigger:
  branches:
    include:
      - main  # Adjust if your default branch is different (e.g., master)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  # You can define additional variables here if needed for your pipeline.

steps:
  # Step 1: Checkout the repository
  - task: Checkout@1  # Using Checkout version 1 to fix the task error
    displayName: 'Checkout Repository'

  # Step 2: Install Node.js (Using NodeTool task)
  - task: UseNode@1
    inputs:
      versionSpec: '16.x'  # Adjust the version as needed
    displayName: 'Install Node.js'

  # Step 3: Install dependencies (Assuming npm is used)
  - script: |
      npm install
    displayName: 'Install npm dependencies'

  # Step 4: Build the project (If applicable, e.g., if you need to build the front-end)
  - script: |
      npm run build
    displayName: 'Build Project (if applicable)'

  # Step 5: Publish build artifacts (optional)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)  # Ensure this variable is available
      ArtifactName: drop
      publishLocation: Container
    displayName: 'Publish Artifacts'

