trigger:
  branches:
    include:
      - main  # Or any other branch

pool:
  vmImage: 'ubuntu-latest'  # Using an Ubuntu-based VM for the pipeline

steps:
- task: UsePythonVersion@0  # Use Python version
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: PipInstall@0  # Install Python dependencies
  inputs:
    requirementsFile: 'requirements.txt'

- task: CopyFiles@2  # Copy project files
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Publish artifacts to Azure DevOps
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1  # Deploy to Azure Web App
  inputs:
    appName: '<Your-Azure-WebApp-Name>'  # Replace with your app name
    package: '$(Build.ArtifactStagingDirectory)/drop'

