trigger:
  branches:
    include:
      - main  # Change to 'master' if your branch is called that

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.10'

steps:
# Step 1: Checkout repository
- checkout: self

# Step 2: Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true
  displayName: 'Set up Python'

# Step 3: Install dependencies
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 4: (Optional) Run Flask app - for local test
- script: |
    source venv/bin/activate
    python app.py
  displayName: 'Run Flask app (dev)'
