name: Python package setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use a stable Python version like 3.9 or 3.10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt-dev python3-dev build-essential
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt  # Install your Python dependencies

    - name: Run tests (if any)
      run: |
        # If you have tests or any other commands to run
        python -m unittest discover

